### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Jimmysit0** [warpwm/lule#2]
▲ ~/lule ./lule --image=/home/jimmy/Pictures/Wallpapers/candyxd.png --palette=convert set                                                                                                                                        main 7h ⬢
[pastel error]: Could not parse color '#E2AAD2FF'
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
[pastel error]: Could not parse color ''
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
[pastel error]: Could not parse color ''
error: The following required arguments were not provided:
    <color>

USAGE:
    pastel mix <color> --colorspace <name> --fraction <fraction> [color]...

For more information try --help
error: The following required arguments were not provided:
    <color>

USAGE:
    pastel mix <color> --colorspace <name> --fraction <fraction> [color]...

For more information try --help
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
[pastel error]: A color argument needs to be provided on the command line or via a pipe. Call this command again with '-h' or '--help' to get more information.
error: The following required arguments were not provided:
    <color>...

USAGE:
    pastel gradient <color>... --colorspace <name> --number <count>

For more information try --help
error: The following required arguments were not provided:
    <color>...

USAGE:
    pastel gradient <color>... --colorspace <name> --number <count>

For more information try --help
error: The following required arguments were not provided:
    <color>...

USAGE:
    pastel gradient <color>... --colorspace <name> --number <count>

For more information try --help
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
[pastel error]: The number of color arguments must be larger than one
error: The following required arguments were not provided:
    <color>...

USAGE:
    pastel gradient <color>... --colorspace <name> --number <count>

For more information try --help
[pastel error]: The number of color arguments must be larger than one

**Comment by fufexan** [comment]
From what I can tell, you're somehow supplying an #AARRGGBB hex color, whereas pastel only supports #RRGGBB colors.

**Comment by bresilla** [comment]
Yes, as @fufexan said Pastel does not support RGBA but only RGB colors.
he thing is that your `convert` command is doing that in your system.

Try to install/use `pigmnts` or `shcemer2` as palette an see if you have same issue?

**Comment by Jimmysit0** [comment]
It fixes it, thanks. You should fix/have that problem in mind for the future.

**Comment by bresilla** [comment]
@Jimmysit0 Thanks for your feedback.
Actually i am porting it all in RUST, and i am actively working those days (you can check the `dev` branch - still far from working), but everything should be more tightly integrated and everything should work
